main: aliuly\grabbag\Main
api: [1.10.0,1.11.0,1.12.0,2.0.0]
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 2.4.1
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/GrabBag
softdepend: FastTransfer
