main: aliuly\livesigns\Main
api: 1.12.0
load: POSTWORLD
name: LiveSigns
description: "Signs and floating text that change contents (e.g. twitter?)"
version: 1.2.1
author: aliuly
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/LiveSigns

commands:
  livesigns:
    description: "Access to LiveSigns functionality"
    usage: "/livesigns <subcmd> [options]"
    permission: livesigns.cmd
    aliases: ["livesign","ls"]
  floatsigns:
    description: "Access to FloatSigns functionality"
    usage: "/floatsigns <subcmd> [options]"
    permission: floatsigns.cmd
    aliases: ["floatsign","fs"]

permissions:
  livesigns.cmd:
    default: op
    description: Main livesign command
  livesigns.cmd.addrm:
    default: op
    description: Update livesign
  livesigns.cmd.info:
    default: true
    description: Show status of livesigns
  livesigns.cmd.update:
    default: op
    description: Refresh livesigns
  livesigns.cmd.broadcast:
    default: op
    description: Broadcast livesigns in chat
  floatsigns.cmd.ls:
    default: true
    description: Show floating signs
  floatsigns.cmd.addrm:
    default: op
    description: Show floating signs
