name: KillRate
version: 1.0.1
main: aliuly\killrate\Main
api: 1.10.0
load: POSTWORLD
# You have to have at least one of these...
softdepend: [PocketMoney,MassiveEconomy,EconomyAPI]

description: Keep track of the number of kills
author: aliuly

commands:
    killrate:
        description: Show kill rate stats
        usage: "/killrate [stats|top]"
        aliases: [kr]
        permission: killrate.cmd

permissions:
    killrate.cmd:
        default: true
        description: "Give players access to KillRate command"
    killrate.cmd.stats:
        default: true
        description: "Access to stats command"
    killrate.cmd.stats.other:
        default: op
        description: "View other's stats"
    killrate.cmd.rank:
        default: true
        description: "View top players"
