name: KillRate
version: 2.1.1
main: aliuly\killrate\Main
api: 1.12.0
load: POSTWORLD
# You have to have at least one of these...
softdepend: [PocketMoney,MassiveEconomy,EconomyAPI,GoldStd,RankUp]

description: Keep track of the number of kills
author: aliuly
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/KillRate

commands:
  killrate:
    description: Show kill rate stats
    usage: "/killrate [stats|top|give]"
    aliases: [kr]
    permission: killrate.cmd

permissions:
  killrate.cmd:
    default: true
    description: "Give players access to KillRate command"
  killrate.cmd.stats:
    default: true
    description: "Access to stats command"
  killrate.cmd.stats.other:
    default: op
    description: "View other's stats"
  killrate.cmd.rank:
    default: true
    description: "View top players"
  killrate.cmd.give:
    default: op
    description: "Give points to players"
  killrate.signs.place:
    default: op
    description: "Allow to place KillRate signs"
  killrate.signs.use:
    default: true
    description: "Allow to use KillRate signs"
