#!/usr/bin/env php
<?php
echo "RUNNING MAKER SCRIPT...\n";
define('SRCDIR',dirname(realpath(__FILE__))."/");
require_once(SRCDIR."../lib/include.php");
require_once(LIBDIR."maker/gendoc.php");
require_once(LIBDIR."maker/mcgen.php");

gendoc(SRCDIR."README.md",$plugin);
mcgen(SRCDIR."resources/messages",SRCDIR."src");

/*
 * TODO:
 * - copy lib/common/{}.php to <namespace>/common/{}.php
 */
exit("OK\n");
