#!/usr/bin/env php
<?php
echo "RUNNING MAKER SCRIPT...\n";
define('SRCDIR',dirname(realpath(__FILE__))."/");
require_once(SRCDIR."../lib/include.php");
require_once(LIBDIR."maker/gendoc.php");
require_once(LIBDIR."maker/mcgen.php");
require_once(LIBDIR."maker/fix-common.php");

//
// Fix the version number
//
$inp = file_get_contents(LIBDIR."common/MPMU.php");
$new = preg_replace('/const\s+VERSION\s*=\s*".*";/',
						  "const VERSION = \"".$plugin["version"]."\";",
						  $inp);
if ($inp != $new) {
	echo "Updating common/MPMU.php\n";
	file_put_contents(LIBDIR."common/MPMU.php",$new);
}


gendoc(SRCDIR."README.md",$plugin);
//fix_common(SRCDIR,LIBDIR,$plugin);
mcgen(SRCDIR."resources/messages",SRCDIR."src");

//
// Create a manifest for creating examples...
//
$mft = SRCDIR."resources/manifest.txt";
$txt = "";
foreach (glob(SRCDIR."resources/examples/*.php") as $php) {
	$txt .= basename($php)."\n";
}
$old  = file_exists($mft) ? file_get_contents($mft) : "";
if ($old != $txt) file_put_contents($mft,$txt);

exit("OK\n");
