#!/usr/bin/env php
<?php
echo "RUNNING MAKER SCRIPT...\n";
define('SRCDIR',dirname(realpath(__FILE__))."/");

require_once(SRCDIR."../lib/include.php");
require_once(LIBDIR."maker/gendoc2.php");
require_once(LIBDIR."maker/mcgen.php");
require_once(LIBDIR."maker/updcode.php");

update_code(LIBDIR."xPaw",SRCDIR."src/xPaw");
update_code(SRCDIR."../GrabBag/src/aliuly/common",SRCDIR."src/aliuly/common");

//
// Fix the version number
//
$inp = file_get_contents(LIBDIR."common/MPMU.php");
if (preg_match('/const\s+VERSION\s*=\s*"(.*)";/',$inp,$mv)) {
	$version = $mv[1];
	$yaml = file_get_contents(SRCDIR."plugin.yml");
	$new = [];
	foreach (explode("\n",$yaml) as $ln) {
		if (preg_match('/^(\s*version:\s*).*$/',$ln,$mv)) {
			$ln = $mv[1].$version;
		}
		$new[] = $ln;
	}
	if (count($new) > 1) {
		if ($new[count($new)-1] != "") $new[] = "";
	}
	$new = implode("\n",$new);
	if ($new != $yaml) {
		echo "Updating plugin.yml\n";
		file_put_contents(SRCDIR."plugin.yml",$new);
		$plugin["version"] = $version;
	}

}


gendoc2(SRCDIR."src",["README.md"],$plugin);
//gendoc(SRCDIR."README.md",$plugin);
//fix_common(SRCDIR,LIBDIR,$plugin);
mcgen(SRCDIR."resources/messages",SRCDIR."src");

//
// Create download page
//
$dl = SRCDIR."downloads.md";
$icon = "<img src=\"https://raw.githubusercontent.com/alejandroliu/bad-plugins/master/Media/download-icon.png\"/>";
$otxt = file_exists($dl) ? file_get_contents($dl) : "";
$ntxt = "";
$ntxt .= "# Downloads\n";
$ntxt .= "\n";
$fp = popen("cd ".SRCDIR."; git tag -l","r");
$vlst = [];
while (($ln = fgets($fp)) !== false) {
	$ln  = trim($ln);
	if (!preg_match('/^libcommon-/',$ln)) continue;
	$ln = explode("-",$ln);
	$ln = array_pop($ln);
	if (preg_match('/dev/',$ln)) continue;
	$vlst[] = $ln;
}
fclose($fp);
function rversion_compare($a,$b) { return version_compare($b,$a);}
usort($vlst,"rversion_compare");
foreach ($vlst as $v) {
	$url = "https://github.com/alejandroliu/pocketmine-plugins/releases/tag/libcommon-$v";
	$ntxt .= "* <a href=\"$url\">$icon $v</a>\n";
}
if ($ntxt != $otxt) {
	file_put_contents($dl,$ntxt);
}



exit("OK\n");
