main: aliuly\fireblade\FireBlade
api: 1.10.0
load: POSTWORLD

name: FireBlade
description: Turn a Sword into a flaming sword
version: 1.0.2
author: aliuly

commands:
    fireblade:
        description: Turn your sword into a flaming sword
        usage: "/fireblade"
        permission: fireblade.cmd

permissions:
    fireblade.cmd:
        default: true
        description: allow players to use fireblades
