name: BasicHUD
version: 1.0.6
main: aliuly\hud\Main
api: 1.12.0
load: POSTWORLD
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/BasicHUD

description: A configurable heads up display
author: aliuly

commands:
  hud:
    description: Control HUD display
    usage: "/hud [on|off|format]"
    permission: basichud.cmd

permissions:
  basichud.user:
    default: true
    description: Allow players to have an HUD
  basichud.cmd:
    default: true
    description: Allow players to access HUD command
  basichud.cmd.toggle:
    default: true
    description: Allow players to toggle HUD on/off
  basichud.cmd.switch:
    default: op
    description: Allow players to switch formats
