#!/usr/bin/env php
<?php
/*
 * Expand HTML Entities to its UTF-8 equivalents
 */
$cmd = array_shift($argv);
foreach ($argv as $f) {
	if (!file_exists($f)) {
		echo "$f: not found\n";
		continue;
	}
	$input = file_get_contents($f);
	$output = html_entity_decode($input,ENT_NOQUOTES|ENT_HTML5,"UTF-8");
	if ($input !== $output) {
		echo "Converting $f\n";
		file_put_contents($f,$output);
	}
}
