#!/usr/bin/env php
<?php
define('SRCDIR',dirname(realpath(__FILE__))."/");
require_once(SRCDIR."gendoc2.php");
define('CMD',array_shift($argv));
error_reporting(E_ALL);

$mode = 'view';
while (count($argv)) {
  switch ($argv[0]) {
    case "-v":
      $mode = "view";
      array_shift($argv);
      continue;
    case "-w":
      $mode = "write";
      array_shift($argv);
      continue;
  }
  break;
}

foreach ($argv as $f) {
  if (($txt = file_get_contents($f)) === false) {
    die("$f: error reading file\n");
  }
  $txt = analyze_doc(explode("\n",$txt),true);
  while (count($txt)>1 && $txt[count($txt)-1] == "") array_pop($txt);
  $txt[] = "";
  switch($mode) {
    case "view":
      if (count($argv) > 1) echo "$f =====\n";
      echo implode("\n",$txt);
      break;
    case "write":
      file_put_contents($f,implode("\n",$txt));
      break;
    default:
      die("Invalid mode: $mode\n");
  }
}
