#!/usr/bin/env php
<?php
echo "RUNNING MAKER SCRIPT...\n";
define('SRCDIR',dirname(realpath(__FILE__))."/");
require_once(SRCDIR."../lib/include.php");
require_once(LIBDIR."maker/mcgen.php");
require_once(LIBDIR."maker/gendoc.php");
require_once(LIBDIR."maker/fix-common.php");

gendoc(SRCDIR."README.md",$plugin);
fix_common(SRCDIR,LIBDIR,$plugin);
mcgen(SRCDIR."resources/messages",SRCDIR."src");

exit("OK\n");
